#theme: jekyll-theme-slate
remote_theme: pages-themes/minimal@v0.2.0

title: "Physical Activity and Technology Challenge (PhysTech)"
description: "blah blah blah"

show_downloads: false
#google_analytics: 

plugins:
- jekyll-remote-theme 


