#theme: jekyll-theme-slate
remote_theme: pages-themes/minimal@v0.2.0

title: "Physical Activity and Technology Hack Day (PhysTech)"
title-short: PhysTech
description: PhysTech is an international online hackathon for anyone who does, watches or analyzes physical activities - including sports, fitness excercises and recreational practices.

full_url: https://binnovative-boston.github.io/hacktest
logo: /images/logo.png
devpost_url: https://animalhack-2023.devpost.com/
discord_url: https://discord.com/invite/ZBbTxuxND2
email: 

show_downloads: false
#google_analytics: 

plugins:
- jekyll-remote-theme 


